name: glassslipper
favicon: null
layout_spectrum: 0.9656489819753915
typography_spectrum: 0.21386021422222257
title: Glass Slipper
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4c4c4c'
    - '#000000'
    - '#64b8e3'
    - '#d0d0d0'
  brandStrength: 0.8461195859126747
  lightness: 0.4407894047908485
  saturation: 0.1614298210479319
  rhythmicContrast: 0.8004874880425632
purpose: []
